Use printf instead of echo -E
FreeBSD compatibility

diff --git a/share/zmtest b/share/zmtest
--- a/share/zmtest
+++ b/share/zmtest
@@ -4,36 +4,35 @@ bindir="$(dirname "$0")"
 
 ZMB="${bindir}/zmb"
 JQ="$(which jq)"
-ECHO=/bin/echo
 
 usage () {
     status="$1"
     message="$2"
-    "${ECHO}" "${message}" >&2
-    "${ECHO}" "Usage: zmtest [OPTIONS] DOMAIN" >&2
-    "${ECHO}" >&2
-    "${ECHO}" "Options:" >&2
-    "${ECHO}" "  -s URL --server URL   Zonemaster Backend to query. Default is http://localhost:5000/" >&2
-    "${ECHO}" "  --noipv4              Run the test without ipv4." >&2
-    "${ECHO}" "  --noipv6              Run the test without ipv6." >&2
-    "${ECHO}" "  --lang LANG           A language tag. Default is \"en\"." >&2
-    "${ECHO}" "                        Valid values are determined by backend_config.ini." >&2
+    printf "%s" "${message}" >&2
+    echo "Usage: zmtest [OPTIONS] DOMAIN" >&2
+    echo >&2
+    echo "Options:" >&2
+    echo "  -s URL --server URL   Zonemaster Backend to query. Default is http://localhost:5000/" >&2
+    echo "  --noipv4              Run the test without ipv4." >&2
+    echo "  --noipv6              Run the test without ipv6." >&2
+    echo "  --lang LANG           A language tag. Default is \"en\"." >&2
+    echo "                        Valid values are determined by backend_config.ini." >&2
     exit "${status}"
 }
 
 error () {
     status="$1"
     message="$2"
-    "${ECHO}" "error: ${message}" >&2
+    printf "error: %s\n" "${message}" >&2
     exit "${status}"
 }
 
 zmb () {
     server_url="$1"; shift
     json="$("${ZMB}" --server="${server_url}" "$@" 2>&1)" || error 1 "method $1: ${json}"
-    json="$("${ECHO}" -E "${json}" | "${JQ}" -S . 2>/dev/null)" || error 1 "method $1 did not return valid JSON output"
-    error="$("${ECHO}" -E "${json}" | "${JQ}" -e .error 2>/dev/null)" && error 1 "method $1: ${error}"
-    "${ECHO}" -E "${json}"
+    json="$(printf "%s" "${json}" | "${JQ}" -S . 2>/dev/null)" || error 1 "method $1 did not return valid JSON output"
+    error="$(printf "%s" "${json}" | "${JQ}" -e .error 2>/dev/null)" && error 1 "method $1: ${error}"
+    printf "%s" "${json}"
 }
 
 [ -n "${JQ}" ] || error 2 "Dependency not found: jq"
@@ -56,10 +55,10 @@ done
 
 # Start test
 output="$(zmb "${server_url}" start_domain_test --domain "${domain}" --ipv4 "${ipv4}" --ipv6 "${ipv6}")" || exit $?
-testid="$("${ECHO}" -E "${output}" | "${JQ}" -r .result)" || exit $?
-"${ECHO}" -E "testid: ${testid}" >&2
+testid="$(printf "%s" "${output}" | "${JQ}" -r .result)" || exit $?
+printf "testid: %s\n" "${testid}" >&2
 
-if "${ECHO}" -E "${testid}" | grep -qE '[^0-9a-fA-F]' ; then
+if echo "${testid}" | grep -qE '[^0-9a-fA-F]' ; then
     error 1 "start_domain_test did not return a testid: ${testid}"
 fi
 
@@ -67,10 +66,10 @@ fi
 while true
 do
     output="$(zmb "${server_url}" test_progress --testid "${testid}")" || exit $?
-    progress="$("${ECHO}" -E "${output}" | "${JQ}" -r .result)" || exit $?
+    progress="$(printf "%s" "${output}" | "${JQ}" -r .result)" || exit $?
     printf "\r${progress}%% done" >&2
     if [ "${progress}" -eq 100 ] ; then
-        "${ECHO}" >&2
+        echo >&2
         break
     fi
     sleep 1
